import Foundation

public enum SplitPresetSize: Int64, CaseIterable, Identifiable, Sendable {
    case floppy144 = 1457664          // 1.44 MB
    case zip100 = 104857600           // 100 MB
    case cd650 = 681574400            // 650 MB
    case cd700 = 734003200            // 700 MB
    case dvd43 = 4700000000           // 4.3 GB
    case custom1GB = 1073741824       // 1 GB
    
    public var id: Int64 { rawValue }
    
    public var displayName: String {
        switch self {
        case .floppy144: return "1.44 MB (Floppy)"
        case .zip100: return "100 MB (ZIP/Upload)"
        case .cd650: return "650 MB (CD-ROM)"
        case .cd700: return "700 MB (CD-ROM)"
        case .dvd43: return "4.3 GB (DVD)"
        case .custom1GB: return "1.0 GB"
        }
    }
}

public struct SplitConfig: Sendable {
    public let sourceURL: URL
    public let destinationDirectory: URL
    public let chunkSize: Int64
    public let generateChecksum: Bool
    
    public init(
        sourceURL: URL,
        destinationDirectory: URL,
        chunkSize: Int64,
        generateChecksum: Bool = true
    ) {
        self.sourceURL = sourceURL
        self.destinationDirectory = destinationDirectory
        self.chunkSize = max(chunkSize, 1024) // minimum 1 KB
        self.generateChecksum = generateChecksum
    }
}

public struct JoinConfig: Sendable {
    public let firstPartURL: URL
    public let destinationDirectory: URL
    public let customOutputName: String?
    
    public init(
        firstPartURL: URL,
        destinationDirectory: URL,
        customOutputName: String? = nil
    ) {
        self.firstPartURL = firstPartURL
        self.destinationDirectory = destinationDirectory
        self.customOutputName = customOutputName
    }
}

public final class FileSplitJoinEngine: @unchecked Sendable {
    public static let shared = FileSplitJoinEngine()
    
    private init() {}
    
    // MARK: - Split File
    
    public func splitFile(
        config: SplitConfig,
        progress: (@Sendable (Double, String) -> Void)? = nil
    ) throws -> [URL] {
        let fm = FileManager.default
        let sourceURL = config.sourceURL
        let attrs = try fm.attributesOfItem(atPath: sourceURL.path)
        guard let totalSize = (attrs[.size] as? NSNumber)?.int64Value, totalSize > 0 else {
            throw NSError(domain: "FileSplitJoinEngine", code: -1, userInfo: [NSLocalizedDescriptionKey: "Source file is empty or missing"])
        }
        
        let chunkSize = config.chunkSize
        let partCount = Int((totalSize + chunkSize - 1) / chunkSize)
        let digits = max(3, String(partCount).count)
        
        let sourceHandle = try FileHandle(forReadingFrom: sourceURL)
        defer { try? sourceHandle.close() }
        
        var createdParts: [URL] = []
        var totalBytesRead: Int64 = 0
        let baseName = sourceURL.lastPathComponent
        
        for partIndex in 1...partCount {
            let partExt = String(format: "%0\(digits)d", partIndex)
            let partFileName = "\(baseName).\(partExt)"
            let partURL = config.destinationDirectory.appendingPathComponent(partFileName)
            
            fm.createFile(atPath: partURL.path, contents: nil, attributes: nil)
            let partHandle = try FileHandle(forWritingTo: partURL)
            
            var bytesWrittenForPart: Int64 = 0
            let bufferSize = min(1024 * 1024, chunkSize) // up to 1 MB buffer
            
            while bytesWrittenForPart < chunkSize {
                let toRead = Int(min(Int64(bufferSize), chunkSize - bytesWrittenForPart))
                let chunkData = sourceHandle.readData(ofLength: toRead)
                if chunkData.isEmpty { break }
                
                partHandle.write(chunkData)
                bytesWrittenForPart += Int64(chunkData.count)
                totalBytesRead += Int64(chunkData.count)
                
                let progressFrac = min(Double(totalBytesRead) / Double(totalSize), 1.0)
                progress?(progressFrac, "Writing part \(partIndex)/\(partCount)")
            }
            
            try? partHandle.close()
            createdParts.append(partURL)
        }
        
        // Optional checksum file
        if config.generateChecksum {
            let sfvURL = config.destinationDirectory.appendingPathComponent("\(baseName).sfv")
            var sfvContent = "; Checksum file generated by AboveDiff (macOS)\n"
            for part in createdParts {
                if let partData = try? Data(contentsOf: part) {
                    let crc = ChecksumService.shared.calculateCRC32(data: partData)
                    sfvContent += "\(part.lastPathComponent) \(String(format: "%08X", crc))\n"
                }
            }
            try? sfvContent.data(using: .utf8)?.write(to: sfvURL)
        }
        
        return createdParts
    }
    
    // MARK: - Detect Split Parts
    
    public func findSequentialParts(firstPartURL: URL) -> [URL] {
        let parent = firstPartURL.deletingLastPathComponent()
        let filename = firstPartURL.lastPathComponent
        
        // Pattern 1: name.001, name.002
        if let dotIndex = filename.lastIndex(of: ".") {
            let base = String(filename[..<dotIndex])
            let ext = String(filename[filename.index(after: dotIndex)...])
            
            if let num = Int(ext) {
                var parts: [URL] = [firstPartURL]
                var nextNum = num + 1
                let digits = ext.count
                
                while true {
                    let nextExt = String(format: "%0\(digits)d", nextNum)
                    let nextURL = parent.appendingPathComponent("\(base).\(nextExt)")
                    if FileManager.default.fileExists(atPath: nextURL.path) {
                        parts.append(nextURL)
                        nextNum += 1
                    } else {
                        break
                    }
                }
                return parts
            }
        }
        
        return [firstPartURL]
    }
    
    public func suggestedJoinedName(firstPartURL: URL) -> String {
        let filename = firstPartURL.lastPathComponent
        if let dotIndex = filename.lastIndex(of: ".") {
            let ext = String(filename[filename.index(after: dotIndex)...])
            if Int(ext) != nil {
                return String(filename[..<dotIndex])
            }
        }
        return "joined_\(filename)"
    }
    
    // MARK: - Join Files
    
    public func joinFiles(
        config: JoinConfig,
        progress: (@Sendable (Double, String) -> Void)? = nil
    ) throws -> URL {
        let parts = findSequentialParts(firstPartURL: config.firstPartURL)
        guard !parts.isEmpty else {
            throw NSError(domain: "FileSplitJoinEngine", code: -1, userInfo: [NSLocalizedDescriptionKey: "No part files found"])
        }
        
        let outputName = config.customOutputName ?? suggestedJoinedName(firstPartURL: config.firstPartURL)
        let outputURL = config.destinationDirectory.appendingPathComponent(outputName)
        
        let fm = FileManager.default
        if fm.fileExists(atPath: outputURL.path) {
            try fm.removeItem(at: outputURL)
        }
        
        fm.createFile(atPath: outputURL.path, contents: nil, attributes: nil)
        let outHandle = try FileHandle(forWritingTo: outputURL)
        defer { try? outHandle.close() }
        
        var totalBytes: Int64 = 0
        for part in parts {
            if let attrs = try? fm.attributesOfItem(atPath: part.path), let sz = attrs[.size] as? NSNumber {
                totalBytes += sz.int64Value
            }
        }
        
        var currentRead: Int64 = 0
        let bufferSize = 1024 * 1024 // 1 MB
        
        for (index, partURL) in parts.enumerated() {
            let inHandle = try FileHandle(forReadingFrom: partURL)
            
            while autoreleasepool(invoking: {
                let data = inHandle.readData(ofLength: bufferSize)
                if data.isEmpty { return false }
                outHandle.write(data)
                currentRead += Int64(data.count)
                
                if totalBytes > 0 {
                    let frac = min(Double(currentRead) / Double(totalBytes), 1.0)
                    progress?(frac, "Joining part \(index + 1)/\(parts.count)")
                }
                return true
            }) {}
            
            try? inHandle.close()
        }
        
        return outputURL
    }
}
